import "./globals.css";
import { Jura } from "next/font/google";
import { ThemeProvider } from "./components/ThemeProvider";


const jura = Jura({
  subsets: ["latin"],
  variable: "--font-jura",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jura.variable}>
      <body className="antialiased font-sans">
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
